
services:
  langchain:
    build: .
    container_name: langchain_app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000","--reload"] 
    volumes:
      - ./app:/app/app       # Mount your code for live edits
      - ./requirements.txt:/app/requirements.txt
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JIRA_URL=${JIRA_URL}
      - JIRA_TOKEN=${JIRA_TOKEN}
      - JIRA_EMAIL=${JIRA_EMAIL}
      - POSTGRES_URL=postgresql+asyncpg://postgres:postgres@postgres/langchain_db
    ports:
      - "8000:8000"          # if your app serves an API
    restart: unless-stopped
    
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: langchain_db
    ports:
      - "5432:5432"   # Optional: expose to host for local tools (pgAdmin, DBeaver)
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: